// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/repo_service.go

// Package service is a generated GoMock package.
package service

import (
	dto "code-repo/internal/model/dto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepoService is a mock of RepoService interface.
type MockRepoService struct {
	ctrl     *gomock.Controller
	recorder *MockRepoServiceMockRecorder
}

// MockRepoServiceMockRecorder is the mock recorder for MockRepoService.
type MockRepoServiceMockRecorder struct {
	mock *MockRepoService
}

// NewMockRepoService creates a new mock instance.
func NewMockRepoService(ctrl *gomock.Controller) *MockRepoService {
	mock := &MockRepoService{ctrl: ctrl}
	mock.recorder = &MockRepoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoService) EXPECT() *MockRepoServiceMockRecorder {
	return m.recorder
}

// CreateRepo mocks base method.
func (m *MockRepoService) CreateRepo(userID uint64, req dto.CreateRepoRequest) (*dto.RepoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepo", userID, req)
	ret0, _ := ret[0].(*dto.RepoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRepo indicates an expected call of CreateRepo.
func (mr *MockRepoServiceMockRecorder) CreateRepo(userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepo", reflect.TypeOf((*MockRepoService)(nil).CreateRepo), userID, req)
}

// DeleteRepo mocks base method.
func (m *MockRepoService) DeleteRepo(userID, repoID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRepo", userID, repoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRepo indicates an expected call of DeleteRepo.
func (mr *MockRepoServiceMockRecorder) DeleteRepo(userID, repoID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRepo", reflect.TypeOf((*MockRepoService)(nil).DeleteRepo), userID, repoID)
}

// GetRepoDetail mocks base method.
func (m *MockRepoService) GetRepoDetail(repoID uint64) (*dto.RepoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoDetail", repoID)
	ret0, _ := ret[0].(*dto.RepoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepoDetail indicates an expected call of GetRepoDetail.
func (mr *MockRepoServiceMockRecorder) GetRepoDetail(repoID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoDetail", reflect.TypeOf((*MockRepoService)(nil).GetRepoDetail), repoID)
}

// UpdateRepo mocks base method.
func (m *MockRepoService) UpdateRepo(userID, repoID uint64, req dto.UpdateRepoRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRepo", userID, repoID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRepo indicates an expected call of UpdateRepo.
func (mr *MockRepoServiceMockRecorder) UpdateRepo(userID, repoID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRepo", reflect.TypeOf((*MockRepoService)(nil).UpdateRepo), userID, repoID, req)
}
