// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/db/repo_repository.go

// Package db is a generated GoMock package.
package db

import (
	entity "code-repo/internal/model/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepoRepository is a mock of RepoRepository interface.
type MockRepoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepoRepositoryMockRecorder
}

// MockRepoRepositoryMockRecorder is the mock recorder for MockRepoRepository.
type MockRepoRepositoryMockRecorder struct {
	mock *MockRepoRepository
}

// NewMockRepoRepository creates a new mock instance.
func NewMockRepoRepository(ctrl *gomock.Controller) *MockRepoRepository {
	mock := &MockRepoRepository{ctrl: ctrl}
	mock.recorder = &MockRepoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoRepository) EXPECT() *MockRepoRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepoRepository) Create(repo *entity.Repository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepoRepositoryMockRecorder) Create(repo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepoRepository)(nil).Create), repo)
}

// Delete mocks base method.
func (m *MockRepoRepository) Delete(id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepoRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepoRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockRepoRepository) GetByID(id uint64) (*entity.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entity.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepoRepositoryMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepoRepository)(nil).GetByID), id)
}

// GetByNameAndOwner mocks base method.
func (m *MockRepoRepository) GetByNameAndOwner(name string, ownerID uint64) (*entity.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNameAndOwner", name, ownerID)
	ret0, _ := ret[0].(*entity.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNameAndOwner indicates an expected call of GetByNameAndOwner.
func (mr *MockRepoRepositoryMockRecorder) GetByNameAndOwner(name, ownerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNameAndOwner", reflect.TypeOf((*MockRepoRepository)(nil).GetByNameAndOwner), name, ownerID)
}

// ListByOwner mocks base method.
func (m *MockRepoRepository) ListByOwner(ownerID uint64, page, pageSize int, keyword string) ([]entity.Repository, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOwner", ownerID, page, pageSize, keyword)
	ret0, _ := ret[0].([]entity.Repository)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByOwner indicates an expected call of ListByOwner.
func (mr *MockRepoRepositoryMockRecorder) ListByOwner(ownerID, page, pageSize, keyword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOwner", reflect.TypeOf((*MockRepoRepository)(nil).ListByOwner), ownerID, page, pageSize, keyword)
}

// Update mocks base method.
func (m *MockRepoRepository) Update(repo *entity.Repository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", repo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepoRepositoryMockRecorder) Update(repo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepoRepository)(nil).Update), repo)
}

// UpdateFields mocks base method.
func (m *MockRepoRepository) UpdateFields(repoID uint64, updates map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFields", repoID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFields indicates an expected call of UpdateFields.
func (mr *MockRepoRepositoryMockRecorder) UpdateFields(repoID, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFields", reflect.TypeOf((*MockRepoRepository)(nil).UpdateFields), repoID, updates)
}
